
name: Sync to Upstream 

on:
  schedule:
    - cron:  '*/05 * * 12 *'
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync HEAD with upstream latest
    
    

    steps:
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout HEAD
      uses: actions/checkout@v2
      with:
        ref: master

    # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
    - name: Pull upstream changes
      run: |
          git branch
              git remote add upstream https://github.com/spinnaker/igor.git

              # Fetch all the branches of that remote into remote-tracking branches

               git fetch upstream

             # Make sure that you're on your master branch:

              git checkout master


             git rebase upstream/master
    - run: echo "üçè This job's status is ${{ job.status }}."
